# Settings for the app
app:
  # HTML Title
  title: Stomping Ground | Imagine Eakins
  # Header name
  name: Imagine Eakins
  # Small text below the name
  subname: What do you want to see in Eakins Oval?
  # Meta description that will show up in Google search results
  meta_description: A demo of Stomping Ground, from OpenPlans
  # Home page description
  description: What park facilities do you want to see in Eakins Oval? Design your perfect park and share the design! This is a demo of Stomping Ground, a mapping tool from OpenPlans.
