# Settings for the app
app:
  # HTML Title
  title: PS 84 | Safe Routes to School | Stomping Ground
  # Header name
  name: PS 84
  # Small text below the name
  subname: Making streets safer for kids.
  # Meta description that will show up in Google search results
  meta_description: We want our sidewalks and streets to be safe, so that children can walk or bike to school. Please help us by identifying unsafe conditions on your route to school, and giving us suggestions about how to improve them.
  # Home page description
  description: We want our sidewalks and streets to be safe, so that children can walk or bike to school. Please help us by identifying unsafe conditions on your route to school, and giving us suggestions about how to improve them.
